### ISSUE TITLE
Streaming freezes even when file data is downloaded

### ISSUE THREAD

**Issue by genseric** [feross/webtorrent#154]
hello again, 
When i run by index it starts to download other files inside the torrent. after some time it starts to download the file that it should start but the other files that i m not interested are created inside the folder with whole sizes. and the file i want to stream sometimes stops downloading and i see other files being downloaded. 
an example is like this, some animation files inside a torrent, i choose to stream one of the smallest files. The run by index starts creating the files i do not want watch. after a few minutes my file gets some bytes and starts to stream to vlc, but streaming is not healty even if i have a good speed. after 5mins i checked and i saw 200 mbs of downloaded data but my 30mb movie file is not complete.

maybe it s an expected behavior, i don't know.
i run the latest(.9) under osx.

thanks,

**Comment by feross** [comment]
The fix here https://github.com/feross/webtorrent/pull/272 (webtorrent@0.27.2) should resolve this issue.

**Comment by westmark** [comment]
@feross I am still experiencing intermittent freezes while downloading torrents (v 0.30.0). Only using magnet links, so unsure if that has any bearing on the problem. So far all torrents have stalled around 60-80% downloaded. I'm trying to investigate as best I can - is there anything special I can do to produce more info?

I'm running WebTorrent in a NW app. When the freeze occurs I have tried to hit pause in the dev console, but that will invariably crash the entire app. Also the crashDumpDir has been disabled in the current version of NW so no luck there either.

**Comment by westmark** [comment]
Update: While the freezes still do occur, given enough time (1-2 minutes) they will eventually resolve themselves. I've been doing some profiling, but nothing conclusive yet.

**Comment by feross** [comment]
Darn. I'll re-open this issue.

**Comment by feross** [comment]
I haven't seen this issue in a while. Closing.
