### ISSUE TITLE
Airplay Subtitles

### ISSUE THREAD

**Issue by pascalgoty** [feross/webtorrent#262]
I cannot get subtitles to work on my Apple TV.
I've tried srt, vtt, and i get nothing.

It's working with vlc.

Thanks

**Comment by feross** [comment]
Support may need to be added to [`airplay-js`](https://github.com/guerrerocarlos/node-airplay-js). I'm not sure if subtitles are already supported or not.

And we'll need to add support in webtorrent, but that part should be easy.

**Comment by alioygur** [comment]
+1

**Comment by feross** [comment]
This issue should be fixed in `webtorrent-cli` now that that is a separate package.

If someone's looking to fix this, I suggest switching the cli to use https://www.npmjs.com/package/airplayer by @watson since that's what WebTorrent Desktop uses now.

**Comment by deamme** [comment]
@feross airplayer by @watson doesn't fix the subtitles issue though?

**Comment by feross** [comment]
No -- it's unrelated. I just think it'd be better to have the CLI using the same package as the Desktop app.
