### ISSUE TITLE
RTCPeerConnection instances leak CPU even when destroyed

### ISSUE THREAD

**Issue by thelordofthetimes** [feross/webtorrent#551]
I check memory use by webtorrent when download on browser environment. Some issues below

- use more memory when started
- memory usage increase during download
- make browser slow

This is check video on youtube 

[![check-video](http://img.youtube.com/vi/tioQvOd1Ks0/0.jpg)](http://www.youtube.com/watch?v=tioQvOd1Ks0)

**Comment by feross** [comment]
Thanks for the informative video!

If you keep the tab open for longer, does the memory usage keep increasing? Or does it stay constant at 2GB?

**Comment by thelordofthetimes** [comment]
Yes, usage memory increase during play time. And after few minutes, it make other tab slower, you can open youtube and play any HD video with full screen to see

**Comment by feross** [comment]
I think there's a leak in Chrome that happens when you open too many RTCPeerConnections, even if you destroy them later.

Let's use this as the tracking issue for that.

**Comment by thelordofthetimes** [comment]
I think it is leak memory, not leak CPU

**Comment by feross** [comment]
I opened an issue on the WebRTC tracker about the CPU leak: https://bugs.chromium.org/p/webrtc/issues/detail?id=5733

**Comment by thelordofthetimes** [comment]
hi feross,

i am webtorrent user. i see that problem and report for you, but i can not solve that problem

may be other people can do ?

**Comment by feross** [comment]
It appears that the WebRTC CPU leak issue only affected OS X/Linux users on Chrome.

And, **GOOD NEWS**, the issue is fixed in Chrome Canary! https://bugs.chromium.org/p/webrtc/issues/detail?id=5733#c3

We can finally put this issue behind us :)

**Comment by thelordofthetimes** [comment]
we are happy :)

**Comment by yciabaud** [comment]
It looks like this issue is fixed in Chrome 50 too which is the current stable version of the browser. It is very nice to be able to let a webtorrent tab open in chrome without crashing the whole app ;)

Nightmare is over.

**Comment by feross** [comment]
Nice, glad that we're putting these annoying webrtc bugs behind us and the implementation is getting stable.

**Comment by feross** [comment]
@yciabaud FWIW, I still see the issue in Chrome 50. But not in Chrome 51.

**Comment by feross** [comment]
You can test for the issue by opening a new tab and pasting this into the console:

```js
function createPeer () {
  var pc = new webkitRTCPeerConnection({
    iceServers: [
      {
        url: 'stun:23.21.150.121',
        urls: 'stun:23.21.150.121'
      }
    ]
  }, {})

  var channel = pc.createDataChannel(String(Math.floor(Math.random() * 1000000)), {})
  channel.binaryType = 'arraybuffer'
  channel.onmessage = function (event) {}
  channel.onopen = function () {}
  channel.onclose = function () {
    console.log('channel onclose')
  }

  pc.onnegotiationneeded = function () {
    pc.createOffer(function (offer) {
      pc.setLocalDescription(offer, function (offer) {
        console.log('set local description')
      }, onError)
    }, onError)
  }

  function onError (err) {
    console.error(err.message)
  }

  setTimeout(function () {
    pc.close()
    channel.close()
  }, 30000)
}

createPeer()
setInterval(createPeer, 3000)
```

**Comment by yciabaud** [comment]
I ran it for 2 hours without any trouble. Looks like Chrome 50 on Linux is fixed.

**Comment by feross** [comment]
Ah, okay. I'm using Chrome 51 on OS X where it's not fixed yet.

**Comment by thelordofthetimes** [comment]
yes, run chrome in almost unix-like operating system has occur bugs

but i do not know what is problem, we are only wait for chrome developers to fix it
