### ISSUE TITLE
 RangeError('Port should be > 0 and < 65536')

### ISSUE THREAD

**Issue by luisnomad** [feross/webtorrent#572]
It happens after 10 minutes of streaming to --vlc:

UNEXPECTED ERROR: If this is a bug in WebTorrent, report it!
OPEN AN ISSUE: https://github.com/feross/webtorrent/issues

DEBUG INFO: webtorrent 0.72.1, node v4.0.0, darwin x64, exit 1
dgram.js:278
    throw new RangeError('Port should be > 0 and < 65536');
    ^

RangeError: Port should be > 0 and < 65536
    at Socket.send (dgram.js:278:11)
    at RPC.send (/usr/local/lib/node_modules/webtorrent/node_modules/bittorrent-dht/node_modules/k-rpc/node_modules/k-rpc-socket/index.js:129:15)
    at RPC.query (/usr/local/lib/node_modules/webtorrent/node_modules/bittorrent-dht/node_modules/k-rpc/node_modules/k-rpc-socket/index.js:173:8)
    at RPC._query (/usr/local/lib/node_modules/webtorrent/node_modules/bittorrent-dht/node_modules/k-rpc/index.js:146:17)
    at RPC.query (/usr/local/lib/node_modules/webtorrent/node_modules/bittorrent-dht/node_modules/k-rpc/index.js:113:8)
    at DHT._sendPing (/usr/local/lib/node_modules/webtorrent/node_modules/bittorrent-dht/client.js:94:13)
    at DHT.addNode (/usr/local/lib/node_modules/webtorrent/node_modules/bittorrent-dht/client.js:84:8)
    at Wire.<anonymous> (/usr/local/lib/node_modules/webtorrent/lib/torrent.js:583:23)
    at emitOne (events.js:77:13)
    at Wire.emit (events.js:169:7)

**Comment by feross** [comment]
Thanks, @mafintosh says he'll fix it.

**Comment by mafintosh** [comment]
@feross this comes from `addNode` according to the stack. Is webtorrent manually adding nodes somewhere?

**Comment by feross** [comment]
Ah, good catch. It's coming from the PORT message which lets peers tell each other about their DHT ports. See: https://github.com/feross/webtorrent/blob/master/lib/torrent.js#L576-L584

The old DHT used to disregard `addNode` calls with invalid ports. That's fine, I can fix it in webtorrent with a guard.

**Comment by mafintosh** [comment]
nice. yea i think its best to solve it in webtorrent then.

**Comment by feross** [comment]
Fixed in 0.72.2.

**Comment by luisnomad** [comment]
@feross hey! Thanks for the fix! Has it made it to the master branch? I have reinstalled webtorrent and I still have the same issue. For now I have overwritten the changed file myself and it works, but people installing the script will have the same problem.

Cheers!

**Comment by feross** [comment]
This is published on npm as v0.72.2 now. Sorry for the delay, folks!
