### ISSUE TITLE
Webseeds stuck sometime

### ISSUE THREAD

**Issue by nghiemvien** [feross/webtorrent#963]
I created a torrent file with url video in it. Normally when I test with 1 pc, it's work just fine , you can check it here http://webtorrent.bna.vn
When another PC join to watch video, something weird happen, sometime video on PC 1 stop, sometime PC2, and sometime both stop.
Browser doesn't get video from webserver anymore

video : https://www.youtube.com/watch?v=7bUCdWGZRhc&feature=youtu.be
- WebTorrent version: latest version
- Browser name/version: latest Chrome

**Comment by DiegoRBaquero** [comment]
Could you provide debugging logs?

It might be the error where the webseed 'peer' 'chokes' and gets removed

**Comment by boygiandi** [comment]
Here is log from PC1 and PC2. Both got stuck at 12.9%

[webtorrent.bna.vn-pc1-1477823017399.txt](https://github.com/feross/webtorrent/files/560394/webtorrent.bna.vn-pc1-1477823017399.txt)
[webtorrent.bna.vn-pc2-1477823040836.txt](https://github.com/feross/webtorrent/files/560393/webtorrent.bna.vn-pc2-1477823040836.txt)

**Comment by nghiemvien** [comment]
Here is log from PC1 and PC2. Both got stuck at 12.9%

[webtorrent.bna.vn-pc1-1477823017399.txt](https://github.com/feross/webtorrent/files/560396/webtorrent.bna.vn-pc1-1477823017399.txt)
[webtorrent.bna.vn-pc2-1477823040836.txt](https://github.com/feross/webtorrent/files/560395/webtorrent.bna.vn-pc2-1477823040836.txt)

**Comment by nghiemvien** [comment]
This is log from PC1 after I close browser on PC2. I see : 
bittorrent-tracker:websocket-tracker tracker timeout: destroying peer +0ms
webtorrent.min.js:4 simple-peer [0f187ea] destroy (error: null) +0ms

[webtorrent.bna.vn-pc1.2-1477823596482.txt](https://github.com/feross/webtorrent/files/560399/webtorrent.bna.vn-pc1.2-1477823596482.txt)

**Comment by gpetrov** [comment]
Got the same problem when downloading through the webseed it goes only for 17-33% and then it get stuck. Complete event never happens. @feross could you check please?

In my situation the tracker is not always available or it couldn't connect with websockets - but it seems to me that then the webseed should be fully used...

**Comment by xuset** [comment]
Looking at the logs that were posted. The interesting parts are line 2615 in the pc1 log and line 308 in pc2 log. Those lines correspond to the last piece request to the webseed. Immediately following, pc1 and pc2 form a webrtc connection to each other then both destroy the webseed peer. I'm not sure why the webseed peer is being destroyed in this case, but it may have something to do with pc1 and pc2 connecting since everything was fine before.

**Comment by gpetrov** [comment]
@DiegoRBaquero yes we got a regularly a "uninterested"  following by "choke" in our sample at piece 56 out of 160 and the webseed download hangs...

Is it supposed to recover after choke? Now it just hangs forever...

**Comment by gpetrov** [comment]
actually it turns our that web seeds shouldn't choke, so addressed the above with https://github.com/feross/webtorrent/pull/972

**Comment by nghiemvien** [comment]
So, anyone can fix this bug ?

**Comment by rayvahey** [comment]
I just found I had this problem too, it seems to lose the webseed object.
In the meantime if you are using a webseed as a fallback like I am, a quick dirty workaround is to check if the torrent.numPeers is zero. Then torrent.addWebSeed(url)

**Comment by feross** [comment]
Sorry for the delay on this. This was fixed in https://github.com/feross/webtorrent/pull/972. Just published a fix as version 0.98.1.

**Comment by rayvahey** [comment]
Thanks Feross, the fix is working very well.

**Comment by bertofer** [comment]
Hi, I am still having this problem when I put my code online. I made screenshot of the logs

![screen shot 2017-10-11 at 18 28 49](https://user-images.githubusercontent.com/1634229/31453919-0b4ce3e6-aeb4-11e7-9842-e1d968bbfae3.png)

This is not happening when testing locally, but occurs when putting everything in the cloud behind an nginx. Trying to figure out if the nginx is doing something wrong. It's still a weird behaviour, as most of the parts seem to download fine, even in large files, it downloads 99% and then gets stuck. With very small files, it get's stuck when there are a couple of pieces missing. Sometimes it gets the whole file (when small). I am not sure what might be happening.

Any help? Thanks
